kibot:
  version: 1


# preflight:
#   run_erc: false
#   update_xml: true
#   run_drc: true
#   check_zone_fills: true
#   ignore_unconnected: false

 preflight:
   run_erc: false
   update_xml: true
   run_drc: false
   check_zone_fills: true
   ignore_unconnected: true


outputs:
  
  ##########################
  # Gerber File Generation #
  ##########################

  - name: JLCPCB_gerbers
    comment: Gerbers compatible with JLCPCB
    type: gerber
    dir: output/jlcpcb_gerber_and_drill
    options: &gerber_options
      exclude_edge_layer: true
      exclude_pads_from_silkscreen: true
      plot_sheet_reference: false
      plot_footprint_refs: true
      plot_footprint_values: false
      force_plot_invisible_refs_vals: false
      tent_vias: true
      use_protel_extensions: true
      create_gerber_job_file: false
      disable_aperture_macros: true
      gerber_precision: 4.6
      use_gerber_x2_attributes: false
      use_gerber_net_attributes: false
      line_width: 0.1
      subtract_mask_from_silk: true
      inner_extension_pattern: '.g%n'
    layers:
      # Note: a more generic approach is to use 'copper' but then the filenames
      # are slightly different.
      - F.Cu
      - B.Cu
      - In1.Cu
      - In2.Cu
      - In3.Cu
      - In4.Cu
      - In5.Cu
      - In6.Cu
      - F.SilkS
      - B.SilkS
      - F.Mask
      - B.Mask
      - Edge.Cuts

  - name: JLCPCB_drill
    comment: Drill files compatible with JLCPCB
    type: excellon
    dir: output/jlcpcb_gerber_and_drill
    options:
      pth_and_npth_single_file: false
      pth_id: '-PTH'
      npth_id: '-NPTH'
      metric_units: true
      map: gerber
      route_mode_for_oval_holes: false
      output: "%f%i.%x"
      

  ################
  # Generate BOM #
  ################
    
  # - name: 'kicad-bom'
  #   comment: "KiCad Bom"
  #   type: kibom
  #   dir: output/bom

  #####################
  # Generate Previews #
  #####################

  # - name: 'Previews'
  #   comment: "preview_render"
  #   type: pcbdraw
  #   dir: output/thumbnails
  #   options:
  #     format: png
