kibot:
  version: 1


# preflight:
#   run_erc: false
#   update_xml: true
#   run_drc: true
#   check_zone_fills: true
#   ignore_unconnected: false

 preflight:
   run_erc: false
   update_xml: true
   run_drc: false
   check_zone_fills: true
   ignore_unconnected: true


outputs:
  
  ##########################
  # Gerber File Generation #
  ##########################

  - name: 'gerbers'
    comment: "Gerbers Files"
    type: gerber
    dir: output/gerber_and_drill
    options:
      # generic layer options
      exclude_edge_layer: false
      exclude_pads_from_silkscreen: false
      plot_sheet_reference: false
      plot_footprint_refs: true
      plot_footprint_values: true
      force_plot_invisible_refs_vals: false
      tent_vias: true
      line_width: 0.15

      # gerber options
      use_aux_axis_as_origin: false
      subtract_mask_from_silk: true
      use_protel_extensions: false
      gerber_precision: 4.5
      create_gerber_job_file: true
      use_gerber_x2_attributes: true
      use_gerber_net_attributes: false

    layers: 'all'

  - name: 'drills'
    comment: "Drill Files"
    type: gerb_drill
    dir: output/gerber_and_drill
    

  ################
  # Generate BOM #
  ################
    
  # - name: 'kicad-bom'
  #   comment: "KiCad Bom"
  #   type: kibom
  #   dir: output/bom

  #####################
  # Generate Previews #
  #####################

  # - name: 'Previews'
  #   comment: "preview_render"
  #   type: pcbdraw
  #   dir: output/thumbnails
  #   options:
  #     format: png
