name: "KiBot Build"

on:
  push:
    paths:
      - '*.kicad_sch'
      - '*.kicad_pcb'
      - '*.kibot.yaml'
      - '.github/workflows/kibot.yml'
  pull_request:
    paths:
      - '*.kicad_sch'
      - '*.kicad_pcb'
      - '*.kibot.yaml'
      - '.github/workflows/kibot.yml'
  repository_dispatch:
    types: [run_qs]

jobs:
  KiBot:
    runs-on: ubuntu-latest
    container: ghcr.io/inti-cmnb/kicad6_auto_full:latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0'

    - name: KiBot
      run: |
        kibot

    - name: Gerber File Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ github.event.repository.name }}-gerber-and-drill-files-${{ github.sha }}
        path: output/gerber_and_drill

    - run: |
        # First attempt to remove thumbnails.
        # This way there will never be "out-of-date" thumbnails
        # It is annoying to have to git pull after every push
        # I am considering only generating the previews on MR/tagged/release/etc
        mkdir thumbnails
        rm thumbnails/*
        
        cp output/thumbnails/* thumbnails/.
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add thumbnails/.
        git commit -m "thumbnails"
        git push

