name: "KiBot Build"

on:
  push:
    paths:
      - '*.kicad_sch'
      - '*.kicad_pcb'
      - '*.kibot.yaml'
      - '.github/workflows/kibot.yml'
  pull_request:
    paths:
      - '*.kicad_sch'
      - '*.kicad_pcb'
      - '*.kibot.yaml'
      - '.github/workflows/kibot.yml'
  repository_dispatch:
    types: [run_qs]



jobs:
  KiBot:
    runs-on: ubuntu-latest
    container: ghcr.io/inti-cmnb/kicad6_auto_full:latest


    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0'


    - name: KiBot
      run: |
        kibot


    - name: JLCPCB Gerber File Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ github.event.repository.name }}-jlcpcb-files-${{ github.sha }}
        path: output/jlcpcb_gerber_and_drill


    # - name: BOM Artifacts
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: ${{ github.event.repository.name }}-BOM-${{ github.sha }}
    #     path: output/bom


    - name: Thumbnails
      if: ${{ github.event.name != 'push' }}
      run: |
        mkdir -p thumbnails
        rm -f thumbnails/* || true        
        cp output/thumbnails/* thumbnails/.
        # git config user.name github-actions
        # git config user.email github-actions@github.com
        # git add thumbnails/.
        # git commit -m "thumbnails"
        # git push

