name: "KiBot"

on:
  push:
    paths:
      - '**/*.kicad*'
      - '**/*.kibot.yaml'

      # This is here for testing
      - '**/kibot-ci.yml'
    tags:
      - '*'

    # Will this cause tags to not work also??
    branches-ignore:
      - 'master'
      - 'main'
      

env:
  GERBERS_JLCPCB: jlcpcb-gerber-${{github.event.repository.name}}-${{github.sha}}-${{github.ref_name}}
      
jobs:
  KiBot:
    runs-on: ubuntu-latest
    container: ghcr.io/inti-cmnb/kicad6_auto_full:latest    
    steps:

    - name: checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
        token: '${{ secrets.PAT_TOKEN }}'

    - name: KiBot
      run: |
        kibot -d output -c .kibot/config.kibot.yaml

    - run: |
        mv ./output/gerber-files/jlcpcb-gerber.zip ./output/gerber-files/${{ env.GERBERS_JLCPCB }}.zip


    # - name: Thumbnails
    #   if: |
    #     (! startsWith(github.ref, 'refs/heads/master')) &&
    #     (! startsWith(github.ref, 'refs/heads/main'))
    #   run: |
    #     mkdir -p thumbnails
    #     rm -f thumbnails/* || true
    #     cp output/thumbnails/* thumbnails/. || true
    #     git config user.name github-actions
    #     git config user.email github-actions@github.com
    #     git add thumbnails/.
    #     (git commit -m "Update Thumbnails" && git push) || true


    # - name: JLCPCB Artifacts
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: ${{ env.GERBERS_JLCPCB }}
    #     path: ./output/gerber-files/${{ env.GERBERS_JLCPCB }}.zip
    #     if-no-files-found: error

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: artifacts-${{github.sha}}
        path: ./output
        if-no-files-found: error
        
    - name: Release Gerbers
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        tag_name: ${{ github.ref_name }}
        files: |
          ./output/gerber-files/${{ env.GERBERS_JLCPCB }}.zip
          ./output/thumbnails/top.png
          ./output/thumbnails/back.png
        #body: "![Preview](./thumbnails/top.png)"

