name: "KiBot - test"

on:
  push:
    tags:
      - '*'
    branches:
      - '*'

env:
  GERBERS_JLCPCB: jlcpcb-gerber-${{github.event.repository.name}}-${{github.sha}}-${{github.ref_name}}
      
jobs:
  KiBot:
    runs-on: ubuntu-latest
    container: ghcr.io/inti-cmnb/kicad6_auto_full:latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0'

    - name: KiBot
      run: |
        kibot -d output -c .kibot/config.kibot.yaml


    # - name: Thumbnails
    #   run: |
    #     mkdir -p thumbnails
    #     rm -f thumbnails/* || true
    #     cp output/thumbnails/* thumbnails/. || true
    #     git config user.name github-actions
    #     git config user.email github-actions@github.com
    #     git add thumbnails/.
    #     (git commit -m "Update Thumbnails" && git push) || true
        
    - name: Thumbnail Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: thumbnail-top.png
        path: output/thumbnails/*top.png
        target: hello-target


    
    - name: JLCPCB Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.GERBERS_JLCPCB }}.zip
        path: output/gerber-files/jlcpcb-gerber.zip
        
    - run: |
        mv output/gerber-files/jlcpcb-gerber.zip ${{ env.GERBERS_JLCPCB }}.zip

    - name: Release Gerbers
      uses: svenstaro/upload-release-action@v2
      #if: startsWith(github.ref, 'refs/tags/')
      with:
        file: ${{ env.GERBERS_JLCPCB }}.zip
        tag: ${{ github.ref_name }}
        overwrite: true
        body: "![Preview](./thumbnails/top.png)"




