name: "KiBot - Thumbnails"

on:
  push:
    paths:
      - '*.kicad*'
      - '*'
  repository_dispatch:
    types: [run_qs]

jobs:
  KiBot:
    runs-on: ubuntu-latest
    container: ghcr.io/inti-cmnb/kicad6_auto_full:latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0'

    - run: env
      # Although it would make sense to have a paired down config file that only generates thumbnails:
      # I don't want mismatched configs to be a possibility. Monolithic config.kibot.yaml only!
    - name: KiBot
      env:
        version: ${{github.ref_name}}
      run: |
        kibot -d output


    - name: Thumbnails
      run: |
        mkdir -p thumbnails
        rm -f thumbnails/* || true
        cp output/thumbnails/* thumbnails/. || true
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add thumbnails/.
        (git commit -m "Update Thumbnails" && git push) || true



