name: "KiBot - Thumbnails"

on:
  push:
    paths:
      - '*.kicad*'
  repository_dispatch:
    types: [run_qs]

jobs:
  KiBot:
    runs-on: ubuntu-latest
    container: ghcr.io/inti-cmnb/kicad6_auto_full:latest


    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0'


    - name: KiBot
      run: |
        kibot


    - name: Thumbnails
      run: |
        mkdir -p thumbnails
        rm -f thumbnails/* || true
        cp output/thumbnails/* thumbnails/. || true
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add thumbnails/.
        (git commit -m "Update Thumbnails" && git push) || true



